# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0023_fiscal_year_default'),
    ]

    operations = [
        migrations.AlterField(
            # migrations.AddField(
            #     model_name='company',
            #     name='is_tag_error_notified',
            #     field=models.BooleanField(default=False, help_text='No Need to Change. Auto Updation Field'),
            # ),
            # migrations.AddField(
            #     model_name='fiscalyearend',
            #     name='is_active',
            #     field=models.BooleanField(default=True),
            # ),
            migrations.AlterField(
                model_name='companymeta',
                name='accounting_setup_status',
                field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'),
                                                            ('ACCOUNTING_TYPE_CHOSEN', 'ACCOUNTING_TYPE_CHOSEN'),
                                                            ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')],
                                       default='NOT_STARTED', max_length=50, null=True),
            ),
            # migrations.AlterModelTable(
            #     name='fiscalyearend',
            #     table=None,
            # ),
        ),
    ]
